#!/bin/bash

echo "Installing useful packages..."
sudo apt -y install compton gcc valgrind glibc-source make vim moc xbacklight tmux doxygen pavucontrol python3-requests python3-bs4
echo "Done!"

echo "Cloning repos..."
git clone https://github.com/weezybusy/dotfiles.git ~/Templates/dotfiles
git clone https://github.com/weezybusy/utils.git ~/Templates/utils
git clone https://github.com/morhetz/gruvbox.git ~/Templates/gruvbox
git clone https://github.com/PapirusDevelopmentTeam/papirus-icon-theme-gtk.git ~/Templates/Papirus
echo "Done!"

echo "Setting links..."
ln -svf /media/$USER/stuff/mus/{salad,jazz,mix} ~/Music
ln -svf /media/$USER/work/{playground,salad,kr2,atbswp} ~/Documents
ln -svf ~/Templates/dotfiles/{.bash_aliases,.bashrc,.gdbinit,.gitconfig,.tmux.conf,.vimrc,.Xresources,.xscreensaver} ~/
ln -svf ~/Templates/dotfiles/compton.conf ~/.config
ln -svf ~/Templates/dotfiles/lxde-rc.xml ~/.config/openbox
ln -svf ~/Templates/Papirus/Papirus-GTK ~/.icons
ln -svf ~/Templates/dotfiles/.themes ~/
mkdir -p ~/.vim
ln -svf ~/Templates/gruvbox/colors ~/.vim
mocp -S
ln -svf ~/Templates/dotfiles/.moc/config ~/.moc/config
echo "Done!"

echo "Unpacking glibc-source..."
sudo tar -xf /usr/src/glibc/glibc-2.19.tar.xz -C /usr/src/glibc
echo "Done!"

echo "Setting up cron..."
crontab -e
echo "Done!"

echo "Fix hanging on copying large files..."
sudo vi /etc/rc.local
echo "Done!"
