#!/bin/bash

echo "Installing useful packages..."
sudo apt-get -y install compton gcc valgrind glibc-source make vim moc xbacklight weechat tmux doxygen pavucontrol
echo "Done!"

echo "Making links to music..."
ln -svf /media/weezy/stuff/mus/{salad,jazz,mix} ~/Music
echo "Done!"

echo "Clonning repos..."
git clone https://github.com/weezybusy/dotfiles.git ~/Templates/dotfiles
git clone https://github.com/morhetz/gruvbox.git ~/Templates/gruvbox
echo "Done!"

echo "Seting links to dotfiles and configs..."
ln -svf ~/Templates/dotfiles/.bash_aliases ~
ln -svf ~/Templates/dotfiles/.bashrc ~/.bashrc
ln -svf ~/Templates/dotfiles/.gdbinit ~/.gdbinit
ln -svf ~/Templates/dotfiles/.gitconfig ~/.gitconfig
ln -svf ~/Templates/dotfiles/.tmux.conf ~/.tmux.conf
ln -svf ~/Templates/dotfiles/.vimrc ~/.vimrc
ln -svf ~/Templates/dotfiles/.Xresources ~/.Xresources
ln -svf ~/Templates/dotfiles/compton.conf ~/.config/compton.conf
ln -svf ~/Templates/dotfiles/lxde-rc.xml ~/.config/openbox/lxde-rc.xml
echo "Done!"

echo "Setting up vim theme..."
mkdir -p ~/.vim
ln -svf ~/Templates/gruvbox/colors ~/.vim
echo "Done!"

echo "Setting up moc..."
mocp -S
ln -svf ~/Templates/dotfiles/.moc/config ~/.moc/config
echo "Done!"

echo "Unpacking glibc-source..."
sudo tar -xf /usr/src/glibc/glibc-2.19.tar.xz -C /usr/src/glibc
echo "Done!"

echo "Setting up crone..."
crontab -e
echo "Done!"

echo "fix hanging on copying large files..."
sudo vi /etc/rc.local
echo "Done!"
