#!/bin/bash

echo "Installing useful packages..."
sudo apt-get -y install compton gcc valgrind glibc-source make vim git moc tmux xbacklight
echo "Done!"

echo "Making links to music..."
ln -s /media/weezy/stuff/mus/{salad,jazz,mix} ~/Music
echo "Done!"

echo "Clonning repos..."
git clone https://github.com/weezybusy/dotfiles.git ~/Templates/dotfiles
git clone https://github.com/morhetz/gruvbox.git ~/Templates/gruvbox
git clone https://github.com/weezybusy/alarm.git

echo "Setting up alarm..."
chmod u+x ~/Templates/alarm/wakeup
echo "Done!"

echo "Seting links to dotfiles and configs..."
ln -svf ~/Templates/dotfiles/.bash_aliases ~
ln -svf ~/Templates/dotfiles/.bashrc ~/.bashrc
ln -svf ~/Templates/dotfiles/.gdbinit ~/.gdbinit
ln -svf ~/Templates/dotfiles/.gitconfig ~/.gitconfig
ln -svf ~/Templates/dotfiles/.tmux.conf ~/.tmux.conf
ln -svf ~/Templates/dotfiles/.vimrc ~/.vimrc
ln -svf ~/Templates/dotfiles/.Xresources ~/.Xresources
ln -svf ~/Templates/dotfiles/configs/compton.conf ~/.config/compton.conf
ln -svf ~/Templates/dotfiles/configs/lxde-rc.xml ~/.config/openbox/lxde-rc.xml
echo "Done!"

echo "Setting up vim..."
mkdir ~/.vim
ln -svf ~/Templates/gruvbox/colors ~/.vim/colors
echo "Done!"

echo "Setting up moc..."
mocp -S
ln -svf ~/Templates/dotfiles/configs/.moc/config ~/.moc/config

echo "Unpacking glibc-source..."
cd /usr/src/glibc
sudo tar xf glibc-2.19.tar.xz
cd

echo "Setting up crone..."
crontab -e
echo "Done!"

echo "fix hanging on copying large files..."
sudo vi /etc/rc.local
echo "Done!"
