#!/bin/bash
apps='gcc valgrind make virtualenv python3-pip moc compton'
sudo apt -y install $apps
pip3 install --upgrade pip
pip3 install --user youtube-dl
git clone https://github.com/weezybusy/dotfiles.git ~/Templates/dotfiles
git clone https://github.com/morhetz/gruvbox.git ~/Templates/gruvbox
git clone https://github.com/PapirusDevelopmentTeam/papirus-icon-theme-gtk.git ~/Templates/papirus
ln -svf /media/$USER/stuff/mus/{salad,jazz} ~/Music
ln -svf /media/$USER/work/{playground,salad,kr2,atbswp} ~/Documents
ln -svf ~/Templates/dotfiles/{.bash_aliases,.bashrc,.gitconfig,.vimrc,.Xresources,.tmux.conf} ~/
ln -svf ~/Templates/dotfiles/compton.conf ~/.config
ln -svf ~/Templates/dotfiles/ubuntu/openbox/lubuntu-rc.xml ~/.config/openbox
mkdir ~/.vim
ln -svf ~/Templates/gruvbox/colors ~/.vim
mocp -S
cp -r /usr/share/moc/themes ~/.moc
ln -svf ~/Templates/dotfiles/ubuntu/config ~/.moc
chmod 644 ~/.moc/config
mkdir ~/.icons
ln -svf ~/Templates/papirus/Papirus-GTK ~/.icons
crontab -e
sudo vi /etc/rc.local
