#!/bin/bash

echo "Installing useful packages..."
apps='compton xbacklight pulseaudio pavucontrol wicd redshift '
apps+='gcc valgrind glibc-source make vim tmux python3-pip '
apps+='firefox-esr moc deluge youtube-dl qalculate xarchiver '
apps+='gparted minidlna lxappearance fonts-roboto dunst'
sudo apt -y install $apps
pip3 install --user youtube-dl pyradio

echo "Cloning repos..."
git clone https://github.com/weezybusy/dotfiles.git ~/Templates/dotfiles
git clone https://github.com/morhetz/gruvbox.git ~/Templates/gruvbox

echo "Setting links..."
ln -svf /media/$USER/stuff/mus/{salad,jazz,stations.csv} ~/Music
ln -svf /media/$USER/work/{playground,salad,kr2,atbswp} ~/Documents
ln -svf ~/Templates/dotfiles/{.bash_aliases,.bashrc,.gdbinit,.gitconfig,.vimrc,.Xresources,.tmux.conf,.profile} ~
ln -svf ~/Templates/dotfiles/{compton.conf,redshift.conf,dunst} ~/.config
ln -svf ~/Templates/dotfiles/lxde-rc.xml ~/.config/openbox
mkdir ~/.vim
ln -svf ~/Templates/gruvbox/colors ~/.vim
mocp -S
ln -svf ~/Templates/dotfiles/config ~/.moc

echo "Unpacking glibc-source..."
sudo tar -xf /usr/src/glibc/glibc-2.19.tar.xz -C /usr/src/glibc

echo "Setting up cron..."
crontab -e

echo "Fix hanging on copying large files..."
sudo vi /etc/rc.local
