#!/bin/bash
# Author: Vitaliy Pisnya

DIRS=(~/.vim ~/.moc ~/.minidlna ~/.local/bin)
DOTS=~/Templates/dotfiles
STUFF=/media/$USER/stuff
TELEGRAMDIR=~/.local/bin/telegram
WORK=/media/$USER/work
APPS="redshift gcc pkg-config libgtk-3-dev valgrind make screen python3-pip
        moc qalculate gparted vim minidlna fonts-roboto gnome-colors racket
        gnome-brave-icon-theme emacs ufw compton xbacklight gmrun deluge
        libav-tools pavucontrol"
PYAPPS="pip youtube-dl"

# Create needed directories.
let i=0
for dir in "${DIRS[@]}"; do
    mkdir -p $dir
done

# Install apps.
sudo apt -y install $APPS
pip3 install --upgrade --user $PYAPPS

# Enable firewall.
echo "Enabling firewall..."
sudo ufw enable && sudo ufw allow 8200

# Download dotfiles.
git clone https://github.com/weezybusy/dotfiles.git $DOTS

# Download vim color schemes.
git clone https://github.com/morhetz/gruvbox.git ~/.vim/gruvbox
git clone https://github.com/chriskempson/tomorrow-theme.git ~/.vim/tomorrow

# Setup indentations for different languages.
mkdir -p "~/.vim/after/ftplugin/"
echo "setlocal shiftwidth=4" >> "~/.vim/after/ftplugin/sh.vim"
echo "setlocal tabstop=4" >> "~/.vim/after/ftplugin/sh.vim"
echo "setlocal shiftwidth=2" >> "~/.vim/after/ftplugin/scheme.vim"
echo "setlocal tabstop=2" >> "~/.vim/after/ftplugin/scheme.vim"

# Make links.
if mount | grep $STUFF > /dev/null; then
    cp -r $STUFF/apps/telegram ~/.local/bin
    chmod +x $TELEGRAMDIR/Telegram
    chmod +x $TELEGRAMDIR/Updater
    ln -svf $STUFF/music/* ~/Music/
    ln -svf $STUFF/videos/* ~/Videos/
fi

if mount | grep $WORK > /dev/null; then
    ln -svf $WORK/* ~/Documents/
fi

if [ -f ~/Documents/lost+found ]; then
    rm ~/Documents/lost+found
fi

ln -svf $DOTS/{.bash_aliases,.bashrc,.gdbinit,.gitconfig,.vimrc,.Xresources,.screenrc,.profile,.emacs} ~
ln -svf $DOTS/{compton.conf,redshift.conf,fontconfig} ~/.config
ln -svf ~/.vim/gruvbox/colors ~/.vim
ln -svf ~/.vim/tomorrow/vim/colors ~/.vim
ln -svf $DOTS/config ~/.moc

# Setup openbox.
mv ~/.config/openbox/lxde-rc.xml ~/.config/openbox/lxde-rc.xml.bak
ln -svf $DOTS/lxde-rc.xml ~/.config/openbox
ln -svf $DOTS/autostart ~/.config/lxsession/LXDE

# Setup minidlna.
sudo mv /etc/minidlna.conf /etc/minidlna.conf.bak
sudo mv /etc/init.d/minidlna /etc/init.d/minidlna.bak
ln -svf $DOTS/minidlna.conf ~/.minidlna
ln -svf $DOTS/minidlna ~/.local/bin
chmod +x ~/.local/bin/minidlna

# Unpack glibc source.
read -p "Do you want to download and unpack glibc library? [y/n]: " input
if [ "$input" = "y" ]; then
    sudo apt -y install glibc-source
    if [ ! -d /usr/src/glibc/glibc-2.19 ]; then
        sudo tar xf /usr/src/glibc/glibc-2.19.tar.xz -C /usr/src/glibc
        sudo rm /usr/src/glibc/glibc-2.19.tar.xz
    fi
fi

# Setup cron jobs.
(crontab -l && echo "0 23 * * * rsync -urv --delete --exclude='/lost+found' $WORK/* $STUFF/work") | crontab -
(crontab -l && echo "0 22 * * * pip3 install --user pip youtube-dl --upgrade") | crontab -
