#!/bin/bash

apps='compton xbacklight pulseaudio pavucontrol redshift gcc valgrind make '
apps+='glibc-source tmux python3-pip moc minidlna vim'
sudo apt -y install $apps
git clone https://github.com/weezybusy/dotfiles.git ~/Templates/dotfiles
git clone https://github.com/morhetz/gruvbox.git ~/Templates/gruvbox
ln -svf /media/$USER/stuff/mus/{salad,jazz} ~/Music
ln -svf /media/$USER/work/sandbox ~/Documents
ln -svf ~/Templates/dotfiles/{.bash_aliases,.bashrc,.gdbinit,.gitconfig,.vimrc,.Xresources,.tmux.conf} ~
ln -svf ~/Templates/dotfiles/{compton.conf,redshift.conf} ~/.config
ln -svf ~/Templates/dotfiles/lxde-rc.xml ~/.config/openbox
mkdir ~/.vim
ln -svf ~/Templates/gruvbox/colors ~/.vim
mocp -S
ln -svf ~/Templates/dotfiles/config ~/.moc
sudo tar xf /usr/src/glibc/glibc-2.19.tar.xz -C /usr/src/glibc
crontab -e
sudo vi /etc/rc.local
