#!/bin/bash
# Author: Vitaliy Pisnya

DOTS=~/Templates/dotfiles
STUFF=/media/$USER/stuff
WORK=/media/$USER/work

# Install apps.
sudo apt -y install compton pcmanfm gmrun xbacklight pavucontrol \
    redshift gcc valgrind make glibc-source tmux python3-pip moc wicd \
    minidlna qalculate gparted deluge firefox-esr vim gnome-icon-theme \
    lxappearance alsa-utils
pip3 install --upgrade --user pip youtube-dl pyradio

# Get dot-files.
if [ ! -d $DOTS ]; then
        git clone https://github.com/weezybusy/dotfiles.git $DOTS
fi

# Make links.
if mount | grep $STUFF > /dev/null; then
        cp -r $STUFF/telegram ~/.local/bin
        chmod +x Telegram Updater
        ln -svf $STUFF/music/* ~/Music/
fi

if mount | grep $WORK > /dev/null; then
        ln -svf $WORK/* ~/Documents/
fi

if [ -f ~/Documents/lost+found ]; then
        rm ~/Documents/lost+found
fi

ln -svf $DOTS/{.bash_aliases,.bashrc,.gdbinit,.gitconfig,.vimrc,.Xresources,.tmux.conf,.profile} ~
ln -svf $DOTS/{compton.conf,redshift.conf,fontconfig} ~/.config

if [ ! -d ~/.config/openbox ]; then
        mkdir ~/.config/openbox
fi
ln -svf $DOTS/{rc.xml,autostart} ~/.config/openbox

if [ ! -d ~/.vim ]; then
        mkdir ~/.vim
fi

if [ ! -d ~/.vim/gruvbox ]; then
        git clone https://github.com/morhetz/gruvbox.git ~/.vim/gruvbox
        ln -svf ~/.vim/gruvbox/colors ~/.vim
fi

if [ ! $(pgrep mocp) ]; then
        mocp -S
fi
ln -svf $DOTS/config ~/.moc

# Setup minidlna.
sudo mv /etc/init.d/minidlna /etc/init.d/minidlna.bak
sudo mv /etc/minidlna.conf /etc/minidlna.conf.bak
if [ ! -d ~/.minidlna ]; then
        mkdir ~/.minidlna
fi
cp $DOTS/minidlna.conf ~/.minidlna
cp $DOTS/minidlna ~/.local/bin

# Unpack glibc source.
if [ ! -d /usr/src/glibc/glibc-2.19 ]; then
        sudo tar xf /usr/src/glibc/glibc-2.19.tar.xz -C /usr/src/glibc
        sudo rm /usr/src/glibc/glibc-2.19.tar.xz
fi

# Get ability to use bitmap fonts.
if [ -f /etc/fonts/conf.d/70-no-bitmaps.conf ]; then
        sudo rm /etc/fonts/conf.d/70-no-bitmaps.conf
fi

# Setup cron jobs.
(crontab -l && echo "0 23 * * * rsync -urv --delete --exclude='/lost+found $WORK/* $STUFF/work") | crontab -

