#!/bin/bash

su -c 'apt install sudo gcc valgrind glibc-source make vim gnome-icon-theme gnome-icon-theme-exrtas xpdf moc youtube-dl feh htop qalculate'

git clone https://github.com/morhetz/gruvbox.git ~/Templates/gruvbox

echo "Setting links..."
ln -svf /media/$USER/stuff/mus/{salad,jazz} ~/Music
ln -svf /media/$USER/work/{playground,salad,kr2,atbswp} ~/Documents
ln -svf ~/Templates/dotfiles/{.bash_aliases,.bashrc,.gdbinit,.gitconfig,.vimrc,.Xresources,.gmrunrc} ~/
ln -svf ~/Templates/dotfiles/compton.conf ~/.config
mkdir ~/.vim
ln -svf ~/Templates/gruvbox/colors ~/.vim
ln -svf ~/Templates/dotfiles/.moc ~/
echo "Done!"

echo "Unpacking glibc-source..."
su -c 'tar -xf /usr/src/glibc/glibc-2.19.tar.xz -C /usr/src/glibc'
echo "Done!"

echo "Fix hanging on copying large files..."
su -c 'vi /etc/rc.local'
echo "Done!"
