#!/bin/bash

echo "Installing aps..."
apps="gcc valgrind glibc-source make vim tmux weechat moc htop mplayer qalculate "
apps+="python3-pip virtualenv python3-bs4, python3-requests"
sudo apt -y install $apps
pip3 install --user tmuxp youtube-dl
echo "Done!"

echo "Cloning repos..."
git clone https://github.com/weezybusy/dotfiles.git ~/Templates/dotfiles
git clone https://github.com/morhetz/gruvbox.git ~/Templates/gruvbox
echo "Done!"

echo "Setting links..."
ln -svf /media/$USER/stuff/mus/{salad,jazz} ~/Music
ln -svf /media/$USER/work/{playground,salad,kr2,atbswp} ~/Documents
ln -svf ~/Templates/dotfiles/{.bash_aliases,.bashrc,.gdbinit,.gitconfig,.vimrc,.Xresources,.tmux.conf,.profile,.tmuxp,.gmrunrc} ~/
ln -svf ~/Templates/dotfiles/compton.conf ~/.config
mkdir ~/.vim
ln -svf ~/Templates/gruvbox/colors ~/.vim
ln -svf ~/Templates/dotfiles/.moc ~/
echo "Done!"

echo "Unpacking glibc-source..."
sudo 'tar -xf /usr/src/glibc/glibc-2.19.tar.xz -C /usr/src/glibc'
echo "Done!"

echo "Setting up cron..."
crontab -e
echo "Done!"

echo "Fix hanging on copying large files..."
sudo 'vi /etc/rc.local'
echo "Done!"
