#!/bin/bash

echo "Installing apps..."
apps="alsa-utils xbacklight firefox compton gcc valgrind glibc-source make "
apps+="python3-pip virtualenv dmenu moc "
sudo apt -y install $apps
pip3 install --user tmuxp youtube-dl
echo "Done!"

echo "Cloning repos..."
git clone https://github.com/weezybusy/dotfiles.git ~/Templates/dotfiles
git clone https://github.com/morhetz/gruvbox.git ~/Templates/gruvbox
echo "Done!"

echo "Setting links..."
ln -svf ~/Templates/dotfiles/{.bash_aliases,.bashrc,.gdbinit,.gitconfig,.vimrc,.Xresources,.tmux.conf,.profile,.tmuxp} ~/
sudo mkdir /mnt/{work,stuff,movie,usb}
ln -svf ~/Templates/dotfiles/compton.conf ~/.config
mkdir ~/.vim
ln -svf ~/Templates/gruvbox/colors ~/.vim
mocp -S
cp -r /usr/share/moc/themes ~/.moc
ln -svf ~/Templates/dotfiles/ubuntu/config ~/.moc
chmod 644 ~/.moc/config
echo "Done!"

echo "Unpacking glibc-source..."
sudo tar -xf /usr/src/glibc/*.tar.xz -C /usr/src/glibc
echo "Done!"

echo "Setting up cron..."
crontab -e
echo "Done!"

echo "Fix hanging on copying large files..."
sudo vi /etc/rc.local
echo "Done!"
